# Site settings
title: "Learn from my experience"
header-img: img/home-bg.jpg
email: svijaykoushik@hotmail.com
copyright_name: Vijaykoushik, S
copyright_start_year: 2017
description: "My experiences with computers, the problems I faced and the fun I had with them and sometimes the topics that interest me find a place in this blog"
keywords: "Computers, electronics, personal experiences, technology, blog"
baseurl: "/blog"
url: "https://svijaykoushik.github.io"
github_username:  svijaykoushik
facebook_username:  svijaykoushik
instagram_username: svijaykoushik
email_username:  svijaykoushik@hotmail.com
twitter_username: vijaykoushiks
site_author: "Vijay Koushik"
# Google Analytics
google_tracking_id: UA-50702630-4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap]

# og settings
og_type: website

#Webmaster settings
google_site_verification: "mhd6MlbydXT7Gl524E0vQuvzfAEbkwphmNjN_AfI0EM"
bing_msvalidate: "A953EBBC10969DE86619DB2BD101AC17"