# Site settings
title: Vijaykoushik's blogs
header-img: img/home-bg.jpg
email: svijaykoushik@hotmail.com
copyright_name: Vijaykoushik
description: "A place where I share my personal experience with computers and technology"
baseurl: "/blog"
url: "https://svijaykoushik.github.io"
github_username:  svijaykoushik
facebook_username:  svijaykoushik
instagram_username: svijaykoushik
email_username:  svijaykoushik@hotmail.com
# Google Analytics
google_analytics: UA-50702630-4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","README.md"]

gems: [jekyll-paginate, jekyll-feed]
