# Site settings
title: "Vijaykoushik's blogs"
header-img: img/home-bg.jpg
email: svijaykoushik@hotmail.com
copyright_name: Vijaykoushik
description: "My experiences with computers, the problems I faced and the fun I had with them and sometimes the topics that interest me find a place in this blog"
keywords: "Computers, electronics, personal experiences, technology, blog"
baseurl: "/blog"
url: "https://svijaykoushik.github.io"
github_username:  svijaykoushik
facebook_username:  svijaykoushik
instagram_username: svijaykoushik
email_username:  svijaykoushik@hotmail.com
# Google Analytics
google_analytics: UA-50702630-4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# og settings
og_type: website
